version: 2

jobs:
  test:
    docker:
      - image: 167617790971.dkr.ecr.us-west-1.amazonaws.com/circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Install and test
          command: yarn install && yarn test
      - run:
          name: Tag new version in GitHub
          command: |
            tag="v$(cat package.json | jq -r .version)"
            is_missing_tag=$(git tag | (grep "^$tag$" || true) | wc -l)

            if [[ "$is_missing_tag" -eq "0" ]]; then
              # Let's make a new release!
              git tag $tag
              git push origin --tags
            fi
  tag:
    docker:
      - image: 167617790971.dkr.ecr.us-west-1.amazonaws.com/circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Tag new version in GitHub
          command: |
            tag="v$(cat package.json | jq -r .version)"
            is_missing_tag=$(git tag | (grep "^$tag$" || true) | wc -l)

            if [[ "$is_missing_tag" -eq "0" ]]; then
              # Let's make a new release!
              git tag $tag
              git push origin --tags
            fi
workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - tag:
          filters:
            branches:
              only:
                - master
