version: 2

jobs:
  test:
    docker:
      - image: 167617790971.dkr.ecr.us-west-1.amazonaws.com/circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Install and test
          command: yarn install && yarn test
workflows:
  version: 2
  test:
    jobs:
      - test
